### ISSUE TITLE
build-kit --help does not work

### ISSUE THREAD

**Issue by EmmEff** [UnivaCorporation/tortuga#159]
Results in a Python traceback:

```shell
(tortuga-243HPvMv) bash-3.2$ build-kit --help
KitBuilder: Getting kit metadata...
Traceback (most recent call last):
  File "/Users/mfrisch/.local/share/virtualenvs/tortuga-243HPvMv/bin/build-kit", line 11, in <module>
    load_entry_point('tortuga-core', 'console_scripts', 'build-kit')()
  File "/Users/mfrisch/Devel/tortuga/src/core/src/tortuga/scripts/build_kit.py", line 67, in main
    BuildKit().run()
  File "/Users/mfrisch/Devel/tortuga/src/core/src/tortuga/scripts/build_kit.py", line 37, in __init__
    self._kit_builder = KitBuilder()
  File "/Users/mfrisch/Devel/tortuga/src/core/src/tortuga/kit/builder.py", line 60, in __init__
    self._kit_meta = KitBuilder.get_kit_metadata()
  File "/Users/mfrisch/Devel/tortuga/src/core/src/tortuga/kit/builder.py", line 101, in get_kit_metadata
    'No kit metadata file found: {}'.format(KIT_METADATA_FILE))
tortuga.exceptions.kitBuildError.KitBuildError: No kit metadata file found: kit.json
```

**Comment by EmmEff** [comment]
`KitBuilder` class was prematurely initialized
